package co.com.academica.model;

import co.com.academica.model.TblCurso;
//import co.com.academica.model.TblCurso;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblCursoMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table tbl_curso
     *
     * @mbggenerated
     */
    int countByExample();

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table tbl_curso
     *
     * @mbggenerated
     */
    int deleteByExample(TblCurso example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table tbl_curso
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer numcurso);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table tbl_curso
     *
     * @mbggenerated
     */
    int insert(TblCurso record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table tbl_curso
     *
     * @mbggenerated
     */
    int insertSelective(TblCurso record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table tbl_curso
     *
     * @mbggenerated
     */
    List<TblCurso> selectByExampleWithBLOBs(TblCurso example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table tbl_curso
     *
     * @mbggenerated
     */
    List<TblCurso> selectByExample(TblCurso example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table tbl_curso
     *
     * @mbggenerated
     */
    TblCurso selectByPrimaryKey(Integer numcurso);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table tbl_curso
     *
     * @mbggenerated
     */
    List<TblCurso> getCursos();

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table tbl_curso
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblCurso record, @Param("example") TblCurso example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table tbl_curso
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") TblCurso record, @Param("example") TblCurso example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table tbl_curso
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblCurso record, @Param("example") TblCurso example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table tbl_curso
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblCurso record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table tbl_curso
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TblCurso record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table tbl_curso
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblCurso record);
}