package co.com.academica.model;

import java.io.Serializable;
import java.util.Date;

public class TblCurso implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_curso.numcurso
     *
     * @mbggenerated
     */
    private Integer numcurso;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_curso.strnombre
     *
     * @mbggenerated
     */
    private String strnombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_curso.dtmfecharegistro
     *
     * @mbggenerated
     */
    private Date dtmfecharegistro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_curso.strobservaciones
     *
     * @mbggenerated
     */
    private String strobservaciones;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_curso
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_curso.numcurso
     *
     * @return the value of tbl_curso.numcurso
     *
     * @mbggenerated
     */
    public Integer getNumcurso() {
        return numcurso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_curso.numcurso
     *
     * @param numcurso the value for tbl_curso.numcurso
     *
     * @mbggenerated
     */
    public void setNumcurso(Integer numcurso) {
        this.numcurso = numcurso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_curso.strnombre
     *
     * @return the value of tbl_curso.strnombre
     *
     * @mbggenerated
     */
    public String getStrnombre() {
        return strnombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_curso.strnombre
     *
     * @param strnombre the value for tbl_curso.strnombre
     *
     * @mbggenerated
     */
    public void setStrnombre(String strnombre) {
        this.strnombre = strnombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_curso.dtmfecharegistro
     *
     * @return the value of tbl_curso.dtmfecharegistro
     *
     * @mbggenerated
     */
    public Date getDtmfecharegistro() {
        return dtmfecharegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_curso.dtmfecharegistro
     *
     * @param dtmfecharegistro the value for tbl_curso.dtmfecharegistro
     *
     * @mbggenerated
     */
    public void setDtmfecharegistro(Date dtmfecharegistro) {
        this.dtmfecharegistro = dtmfecharegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_curso.strobservaciones
     *
     * @return the value of tbl_curso.strobservaciones
     *
     * @mbggenerated
     */
    public String getStrobservaciones() {
        return strobservaciones;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_curso.strobservaciones
     *
     * @param strobservaciones the value for tbl_curso.strobservaciones
     *
     * @mbggenerated
     */
    public void setStrobservaciones(String strobservaciones) {
        this.strobservaciones = strobservaciones;
    }
 
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_curso
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TblCurso other = (TblCurso) that;
        return (this.getNumcurso() == null ? other.getNumcurso() == null : this.getNumcurso().equals(other.getNumcurso()))
            && (this.getStrnombre() == null ? other.getStrnombre() == null : this.getStrnombre().equals(other.getStrnombre()))
            && (this.getDtmfecharegistro() == null ? other.getDtmfecharegistro() == null : this.getDtmfecharegistro().equals(other.getDtmfecharegistro()))
            && (this.getStrobservaciones() == null ? other.getStrobservaciones() == null : this.getStrobservaciones().equals(other.getStrobservaciones()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_curso
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getNumcurso() == null) ? 0 : getNumcurso().hashCode());
        result = prime * result + ((getStrnombre() == null) ? 0 : getStrnombre().hashCode());
        result = prime * result + ((getDtmfecharegistro() == null) ? 0 : getDtmfecharegistro().hashCode());
        result = prime * result + ((getStrobservaciones() == null) ? 0 : getStrobservaciones().hashCode());
        return result;
    }
}