package co.com.academica.model;

import java.io.Serializable;

public class TblCiudades implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ciudades.numciudad
     *
     * @mbggenerated
     */
    private Integer numciudad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ciudades.strciudad
     *
     * @mbggenerated
     */
    private String strciudad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_ciudades
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ciudades.numciudad
     *
     * @return the value of tbl_ciudades.numciudad
     *
     * @mbggenerated
     */
    public Integer getNumciudad() {
        return numciudad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ciudades.numciudad
     *
     * @param numciudad the value for tbl_ciudades.numciudad
     *
     * @mbggenerated
     */
    public void setNumciudad(Integer numciudad) {
        this.numciudad = numciudad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ciudades.strciudad
     *
     * @return the value of tbl_ciudades.strciudad
     *
     * @mbggenerated
     */
    public String getStrciudad() {
        return strciudad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ciudades.strciudad
     *
     * @param strciudad the value for tbl_ciudades.strciudad
     *
     * @mbggenerated
     */
    public void setStrciudad(String strciudad) {
        this.strciudad = strciudad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ciudades
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TblCiudades other = (TblCiudades) that;
        return (this.getNumciudad() == null ? other.getNumciudad() == null : this.getNumciudad().equals(other.getNumciudad()))
            && (this.getStrciudad() == null ? other.getStrciudad() == null : this.getStrciudad().equals(other.getStrciudad()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ciudades
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getNumciudad() == null) ? 0 : getNumciudad().hashCode());
        result = prime * result + ((getStrciudad() == null) ? 0 : getStrciudad().hashCode());
        return result;
    }
}