package co.com.academica.model;

import java.io.Serializable;
import java.util.Date;

public class TblCalendarioMateria implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_calendario_materia.numcalendario
     *
     * @mbggenerated
     */
    private Integer numcalendario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_calendario_materia.nummateria
     *
     * @mbggenerated
     */
    private Integer nummateria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_calendario_materia.dtmhorainicial
     *
     * @mbggenerated
     */
    private String dtmhorainicial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_calendario_materia.dtmhorafinal
     *
     * @mbggenerated
     */
    private String dtmhorafinal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_calendario_materia.strdia
     *
     * @mbggenerated
     */
    private String strdia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_calendario_materia.strobservaciones
     *
     * @mbggenerated
     */
    private String strobservaciones;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_calendario_materia.dtmfecharegistro
     *
     * @mbggenerated
     */
    private Date dtmfecharegistro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_calendario_materia
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_calendario_materia.numcalendario
     *
     * @return the value of tbl_calendario_materia.numcalendario
     *
     * @mbggenerated
     */
    public Integer getNumcalendario() {
        return numcalendario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_calendario_materia.numcalendario
     *
     * @param numcalendario the value for tbl_calendario_materia.numcalendario
     *
     * @mbggenerated
     */
    public void setNumcalendario(Integer numcalendario) {
        this.numcalendario = numcalendario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_calendario_materia.nummateria
     *
     * @return the value of tbl_calendario_materia.nummateria
     *
     * @mbggenerated
     */
    public Integer getNummateria() {
        return nummateria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_calendario_materia.nummateria
     *
     * @param nummateria the value for tbl_calendario_materia.nummateria
     *
     * @mbggenerated
     */
    public void setNummateria(Integer nummateria) {
        this.nummateria = nummateria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_calendario_materia.dtmhorainicial
     *
     * @return the value of tbl_calendario_materia.dtmhorainicial
     *
     * @mbggenerated
     */
    public String getDtmhorainicial() {
        return dtmhorainicial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_calendario_materia.dtmhorainicial
     *
     * @param dtmhorainicial the value for tbl_calendario_materia.dtmhorainicial
     *
     * @mbggenerated
     */
    public void setDtmhorainicial(String dtmhorainicial) {
        this.dtmhorainicial = dtmhorainicial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_calendario_materia.dtmhorafinal
     *
     * @return the value of tbl_calendario_materia.dtmhorafinal
     *
     * @mbggenerated
     */
    public String getDtmhorafinal() {
        return dtmhorafinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_calendario_materia.dtmhorafinal
     *
     * @param dtmhorafinal the value for tbl_calendario_materia.dtmhorafinal
     *
     * @mbggenerated
     */
    public void setDtmhorafinal(String dtmhorafinal) {
        this.dtmhorafinal = dtmhorafinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_calendario_materia.strdia
     *
     * @return the value of tbl_calendario_materia.strdia
     *
     * @mbggenerated
     */
    public String getStrdia() {
        return strdia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_calendario_materia.strdia
     *
     * @param strdia the value for tbl_calendario_materia.strdia
     *
     * @mbggenerated
     */
    public void setStrdia(String strdia) {
        this.strdia = strdia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_calendario_materia.strobservaciones
     *
     * @return the value of tbl_calendario_materia.strobservaciones
     *
     * @mbggenerated
     */
    public String getStrobservaciones() {
        return strobservaciones;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_calendario_materia.strobservaciones
     *
     * @param strobservaciones the value for tbl_calendario_materia.strobservaciones
     *
     * @mbggenerated
     */
    public void setStrobservaciones(String strobservaciones) {
        this.strobservaciones = strobservaciones;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_calendario_materia.dtmfecharegistro
     *
     * @return the value of tbl_calendario_materia.dtmfecharegistro
     *
     * @mbggenerated
     */
    public Date getDtmfecharegistro() {
        return dtmfecharegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_calendario_materia.dtmfecharegistro
     *
     * @param dtmfecharegistro the value for tbl_calendario_materia.dtmfecharegistro
     *
     * @mbggenerated
     */
    public void setDtmfecharegistro(Date dtmfecharegistro) {
        this.dtmfecharegistro = dtmfecharegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_calendario_materia
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TblCalendarioMateria other = (TblCalendarioMateria) that;
        return (this.getNumcalendario() == null ? other.getNumcalendario() == null : this.getNumcalendario().equals(other.getNumcalendario()))
            && (this.getNummateria() == null ? other.getNummateria() == null : this.getNummateria().equals(other.getNummateria()))
            && (this.getDtmhorainicial() == null ? other.getDtmhorainicial() == null : this.getDtmhorainicial().equals(other.getDtmhorainicial()))
            && (this.getDtmhorafinal() == null ? other.getDtmhorafinal() == null : this.getDtmhorafinal().equals(other.getDtmhorafinal()))
            && (this.getStrdia() == null ? other.getStrdia() == null : this.getStrdia().equals(other.getStrdia()))
            && (this.getStrobservaciones() == null ? other.getStrobservaciones() == null : this.getStrobservaciones().equals(other.getStrobservaciones()))
            && (this.getDtmfecharegistro() == null ? other.getDtmfecharegistro() == null : this.getDtmfecharegistro().equals(other.getDtmfecharegistro()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_calendario_materia
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getNumcalendario() == null) ? 0 : getNumcalendario().hashCode());
        result = prime * result + ((getNummateria() == null) ? 0 : getNummateria().hashCode());
        result = prime * result + ((getDtmhorainicial() == null) ? 0 : getDtmhorainicial().hashCode());
        result = prime * result + ((getDtmhorafinal() == null) ? 0 : getDtmhorafinal().hashCode());
        result = prime * result + ((getStrdia() == null) ? 0 : getStrdia().hashCode());
        result = prime * result + ((getStrobservaciones() == null) ? 0 : getStrobservaciones().hashCode());
        result = prime * result + ((getDtmfecharegistro() == null) ? 0 : getDtmfecharegistro().hashCode());
        return result;
    }
}