package co.com.academica.model;

import java.io.Serializable;
import java.util.Date;

public class TblDocentes implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_docentes.numdocente
     *
     * @mbggenerated
     */
    private Integer numdocente;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_docentes.strcodigo
     *
     * @mbggenerated
     */
    private String strcodigo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_docentes.stridentificacion
     *
     * @mbggenerated
     */
    private String stridentificacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_docentes.strtipoidentificacion
     *
     * @mbggenerated
     */
    private String strtipoidentificacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_docentes.strnombres
     *
     * @mbggenerated
     */
    private String strnombres;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_docentes.dtmfechanacimiento
     *
     * @mbggenerated
     */
    private Date dtmfechanacimiento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_docentes.strdireccion
     *
     * @mbggenerated
     */
    private String strdireccion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_docentes.strtelefono
     *
     * @mbggenerated
     */
    private String strtelefono;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_docentes.strcelular
     *
     * @mbggenerated
     */
    private String strcelular;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_docentes.strciudadresidencia
     *
     * @mbggenerated
     */
    private String strciudadresidencia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_docentes.strsexo
     *
     * @mbggenerated
     */
    private String strsexo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_docentes.numescalafon
     *
     * @mbggenerated
     */
    private Integer numescalafon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_docentes.titulo
     *
     * @mbggenerated
     */
    private String titulo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_docentes.strmail
     *
     * @mbggenerated
     */
    private String strmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_docentes.dtmfecharegistro
     *
     * @mbggenerated
     */
    private Date dtmfecharegistro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_docentes
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_docentes.numdocente
     *
     * @return the value of tbl_docentes.numdocente
     *
     * @mbggenerated
     */
    public Integer getNumdocente() {
        return numdocente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_docentes.numdocente
     *
     * @param numdocente the value for tbl_docentes.numdocente
     *
     * @mbggenerated
     */
    public void setNumdocente(Integer numdocente) {
        this.numdocente = numdocente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_docentes.strcodigo
     *
     * @return the value of tbl_docentes.strcodigo
     *
     * @mbggenerated
     */
    public String getStrcodigo() {
        return strcodigo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_docentes.strcodigo
     *
     * @param strcodigo the value for tbl_docentes.strcodigo
     *
     * @mbggenerated
     */
    public void setStrcodigo(String strcodigo) {
        this.strcodigo = strcodigo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_docentes.stridentificacion
     *
     * @return the value of tbl_docentes.stridentificacion
     *
     * @mbggenerated
     */
    public String getStridentificacion() {
        return stridentificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_docentes.stridentificacion
     *
     * @param stridentificacion the value for tbl_docentes.stridentificacion
     *
     * @mbggenerated
     */
    public void setStridentificacion(String stridentificacion) {
        this.stridentificacion = stridentificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_docentes.strtipoidentificacion
     *
     * @return the value of tbl_docentes.strtipoidentificacion
     *
     * @mbggenerated
     */
    public String getStrtipoidentificacion() {
        return strtipoidentificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_docentes.strtipoidentificacion
     *
     * @param strtipoidentificacion the value for tbl_docentes.strtipoidentificacion
     *
     * @mbggenerated
     */
    public void setStrtipoidentificacion(String strtipoidentificacion) {
        this.strtipoidentificacion = strtipoidentificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_docentes.strnombres
     *
     * @return the value of tbl_docentes.strnombres
     *
     * @mbggenerated
     */
    public String getStrnombres() {
        return strnombres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_docentes.strnombres
     *
     * @param strnombres the value for tbl_docentes.strnombres
     *
     * @mbggenerated
     */
    public void setStrnombres(String strnombres) {
        this.strnombres = strnombres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_docentes.dtmfechanacimiento
     *
     * @return the value of tbl_docentes.dtmfechanacimiento
     *
     * @mbggenerated
     */
    public Date getDtmfechanacimiento() {
        return dtmfechanacimiento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_docentes.dtmfechanacimiento
     *
     * @param dtmfechanacimiento the value for tbl_docentes.dtmfechanacimiento
     *
     * @mbggenerated
     */
    public void setDtmfechanacimiento(Date dtmfechanacimiento) {
        this.dtmfechanacimiento = dtmfechanacimiento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_docentes.strdireccion
     *
     * @return the value of tbl_docentes.strdireccion
     *
     * @mbggenerated
     */
    public String getStrdireccion() {
        return strdireccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_docentes.strdireccion
     *
     * @param strdireccion the value for tbl_docentes.strdireccion
     *
     * @mbggenerated
     */
    public void setStrdireccion(String strdireccion) {
        this.strdireccion = strdireccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_docentes.strtelefono
     *
     * @return the value of tbl_docentes.strtelefono
     *
     * @mbggenerated
     */
    public String getStrtelefono() {
        return strtelefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_docentes.strtelefono
     *
     * @param strtelefono the value for tbl_docentes.strtelefono
     *
     * @mbggenerated
     */
    public void setStrtelefono(String strtelefono) {
        this.strtelefono = strtelefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_docentes.strcelular
     *
     * @return the value of tbl_docentes.strcelular
     *
     * @mbggenerated
     */
    public String getStrcelular() {
        return strcelular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_docentes.strcelular
     *
     * @param strcelular the value for tbl_docentes.strcelular
     *
     * @mbggenerated
     */
    public void setStrcelular(String strcelular) {
        this.strcelular = strcelular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_docentes.strciudadresidencia
     *
     * @return the value of tbl_docentes.strciudadresidencia
     *
     * @mbggenerated
     */
    public String getStrciudadresidencia() {
        return strciudadresidencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_docentes.strciudadresidencia
     *
     * @param strciudadresidencia the value for tbl_docentes.strciudadresidencia
     *
     * @mbggenerated
     */
    public void setStrciudadresidencia(String strciudadresidencia) {
        this.strciudadresidencia = strciudadresidencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_docentes.strsexo
     *
     * @return the value of tbl_docentes.strsexo
     *
     * @mbggenerated
     */
    public String getStrsexo() {
        return strsexo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_docentes.strsexo
     *
     * @param strsexo the value for tbl_docentes.strsexo
     *
     * @mbggenerated
     */
    public void setStrsexo(String strsexo) {
        this.strsexo = strsexo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_docentes.numescalafon
     *
     * @return the value of tbl_docentes.numescalafon
     *
     * @mbggenerated
     */
    public Integer getNumescalafon() {
        return numescalafon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_docentes.numescalafon
     *
     * @param numescalafon the value for tbl_docentes.numescalafon
     *
     * @mbggenerated
     */
    public void setNumescalafon(Integer numescalafon) {
        this.numescalafon = numescalafon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_docentes.titulo
     *
     * @return the value of tbl_docentes.titulo
     *
     * @mbggenerated
     */
    public String getTitulo() {
        return titulo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_docentes.titulo
     *
     * @param titulo the value for tbl_docentes.titulo
     *
     * @mbggenerated
     */
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_docentes.strmail
     *
     * @return the value of tbl_docentes.strmail
     *
     * @mbggenerated
     */
    public String getStrmail() {
        return strmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_docentes.strmail
     *
     * @param strmail the value for tbl_docentes.strmail
     *
     * @mbggenerated
     */
    public void setStrmail(String strmail) {
        this.strmail = strmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_docentes.dtmfecharegistro
     *
     * @return the value of tbl_docentes.dtmfecharegistro
     *
     * @mbggenerated
     */
    public Date getDtmfecharegistro() {
        return dtmfecharegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_docentes.dtmfecharegistro
     *
     * @param dtmfecharegistro the value for tbl_docentes.dtmfecharegistro
     *
     * @mbggenerated
     */
    public void setDtmfecharegistro(Date dtmfecharegistro) {
        this.dtmfecharegistro = dtmfecharegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_docentes
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TblDocentes other = (TblDocentes) that;
        return (this.getNumdocente() == null ? other.getNumdocente() == null : this.getNumdocente().equals(other.getNumdocente()))
            && (this.getStrcodigo() == null ? other.getStrcodigo() == null : this.getStrcodigo().equals(other.getStrcodigo()))
            && (this.getStridentificacion() == null ? other.getStridentificacion() == null : this.getStridentificacion().equals(other.getStridentificacion()))
            && (this.getStrtipoidentificacion() == null ? other.getStrtipoidentificacion() == null : this.getStrtipoidentificacion().equals(other.getStrtipoidentificacion()))
            && (this.getStrnombres() == null ? other.getStrnombres() == null : this.getStrnombres().equals(other.getStrnombres()))
            && (this.getDtmfechanacimiento() == null ? other.getDtmfechanacimiento() == null : this.getDtmfechanacimiento().equals(other.getDtmfechanacimiento()))
            && (this.getStrdireccion() == null ? other.getStrdireccion() == null : this.getStrdireccion().equals(other.getStrdireccion()))
            && (this.getStrtelefono() == null ? other.getStrtelefono() == null : this.getStrtelefono().equals(other.getStrtelefono()))
            && (this.getStrcelular() == null ? other.getStrcelular() == null : this.getStrcelular().equals(other.getStrcelular()))
            && (this.getStrciudadresidencia() == null ? other.getStrciudadresidencia() == null : this.getStrciudadresidencia().equals(other.getStrciudadresidencia()))
            && (this.getStrsexo() == null ? other.getStrsexo() == null : this.getStrsexo().equals(other.getStrsexo()))
            && (this.getNumescalafon() == null ? other.getNumescalafon() == null : this.getNumescalafon().equals(other.getNumescalafon()))
            && (this.getTitulo() == null ? other.getTitulo() == null : this.getTitulo().equals(other.getTitulo()))
            && (this.getStrmail() == null ? other.getStrmail() == null : this.getStrmail().equals(other.getStrmail()))
            && (this.getDtmfecharegistro() == null ? other.getDtmfecharegistro() == null : this.getDtmfecharegistro().equals(other.getDtmfecharegistro()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_docentes
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getNumdocente() == null) ? 0 : getNumdocente().hashCode());
        result = prime * result + ((getStrcodigo() == null) ? 0 : getStrcodigo().hashCode());
        result = prime * result + ((getStridentificacion() == null) ? 0 : getStridentificacion().hashCode());
        result = prime * result + ((getStrtipoidentificacion() == null) ? 0 : getStrtipoidentificacion().hashCode());
        result = prime * result + ((getStrnombres() == null) ? 0 : getStrnombres().hashCode());
        result = prime * result + ((getDtmfechanacimiento() == null) ? 0 : getDtmfechanacimiento().hashCode());
        result = prime * result + ((getStrdireccion() == null) ? 0 : getStrdireccion().hashCode());
        result = prime * result + ((getStrtelefono() == null) ? 0 : getStrtelefono().hashCode());
        result = prime * result + ((getStrcelular() == null) ? 0 : getStrcelular().hashCode());
        result = prime * result + ((getStrciudadresidencia() == null) ? 0 : getStrciudadresidencia().hashCode());
        result = prime * result + ((getStrsexo() == null) ? 0 : getStrsexo().hashCode());
        result = prime * result + ((getNumescalafon() == null) ? 0 : getNumescalafon().hashCode());
        result = prime * result + ((getTitulo() == null) ? 0 : getTitulo().hashCode());
        result = prime * result + ((getStrmail() == null) ? 0 : getStrmail().hashCode());
        result = prime * result + ((getDtmfecharegistro() == null) ? 0 : getDtmfecharegistro().hashCode());
        return result;
    }
}