package co.com.academica.model;

import co.com.academica.model.TblDocentes;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblDocentesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_docentes
     *
     * @mbggenerated
     */
    int countByExample();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_docentes
     *
     * @mbggenerated
     */
    int deleteByExample(TblDocentes example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_docentes
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer numdocente);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_docentes
     *
     * @mbggenerated
     */
    int insert(TblDocentes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_docentes
     *
     * @mbggenerated
     */
    int insertSelective(TblDocentes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_docentes
     *
     * @mbggenerated
     */
    List<TblDocentes> selectByExample(TblDocentes example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_docentes
     *
     * @mbggenerated
     */
    List<TblDocentes> getDocentes();
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_docentes
     *
     * @mbggenerated
     */
    TblDocentes selectByPrimaryKey(Integer numdocente);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_docentes
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblDocentes record, @Param("example") TblDocentes example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_docentes
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblDocentes record, @Param("example") TblDocentes example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_docentes
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblDocentes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_docentes
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblDocentes record);
}