package co.com.academica.model;

import java.io.Serializable;
import java.util.Date;

public class TblEstudiantes implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_estudiantes.numestudiante
     *
     * @mbggenerated
     */
    private Integer numestudiante;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_estudiantes.strcodigo
     *
     * @mbggenerated
     */
    private String strcodigo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_estudiantes.stridentificacion
     *
     * @mbggenerated
     */
    private String stridentificacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_estudiantes.strtipoidentificacion
     *
     * @mbggenerated
     */
    private String strtipoidentificacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_estudiantes.strnombres
     *
     * @mbggenerated
     */
    private String strnombres;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_estudiantes.dtmfechanacimiento
     *
     * @mbggenerated
     */
    private Date dtmfechanacimiento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_estudiantes.strdireccion
     *
     * @mbggenerated
     */
    private String strdireccion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_estudiantes.strtelefono
     *
     * @mbggenerated
     */
    private String strtelefono;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_estudiantes.strciudadresidencia
     *
     * @mbggenerated
     */
    private String strciudadresidencia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_estudiantes.strsexo
     *
     * @mbggenerated
     */
    private String strsexo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_estudiantes.strmail
     *
     * @mbggenerated
     */
    private String strmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_estudiantes.dtmfecharegistro
     *
     * @mbggenerated
     */
    private Date dtmfecharegistro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_estudiantes
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_estudiantes.numestudiante
     *
     * @return the value of tbl_estudiantes.numestudiante
     *
     * @mbggenerated
     */
    public Integer getNumestudiante() {
        return numestudiante;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_estudiantes.numestudiante
     *
     * @param numestudiante the value for tbl_estudiantes.numestudiante
     *
     * @mbggenerated
     */
    public void setNumestudiante(Integer numestudiante) {
        this.numestudiante = numestudiante;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_estudiantes.strcodigo
     *
     * @return the value of tbl_estudiantes.strcodigo
     *
     * @mbggenerated
     */
    public String getStrcodigo() {
        return strcodigo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_estudiantes.strcodigo
     *
     * @param strcodigo the value for tbl_estudiantes.strcodigo
     *
     * @mbggenerated
     */
    public void setStrcodigo(String strcodigo) {
        this.strcodigo = strcodigo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_estudiantes.stridentificacion
     *
     * @return the value of tbl_estudiantes.stridentificacion
     *
     * @mbggenerated
     */
    public String getStridentificacion() {
        return stridentificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_estudiantes.stridentificacion
     *
     * @param stridentificacion the value for tbl_estudiantes.stridentificacion
     *
     * @mbggenerated
     */
    public void setStridentificacion(String stridentificacion) {
        this.stridentificacion = stridentificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_estudiantes.strtipoidentificacion
     *
     * @return the value of tbl_estudiantes.strtipoidentificacion
     *
     * @mbggenerated
     */
    public String getStrtipoidentificacion() {
        return strtipoidentificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_estudiantes.strtipoidentificacion
     *
     * @param strtipoidentificacion the value for tbl_estudiantes.strtipoidentificacion
     *
     * @mbggenerated
     */
    public void setStrtipoidentificacion(String strtipoidentificacion) {
        this.strtipoidentificacion = strtipoidentificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_estudiantes.strnombres
     *
     * @return the value of tbl_estudiantes.strnombres
     *
     * @mbggenerated
     */
    public String getStrnombres() {
        return strnombres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_estudiantes.strnombres
     *
     * @param strnombres the value for tbl_estudiantes.strnombres
     *
     * @mbggenerated
     */
    public void setStrnombres(String strnombres) {
        this.strnombres = strnombres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_estudiantes.dtmfechanacimiento
     *
     * @return the value of tbl_estudiantes.dtmfechanacimiento
     *
     * @mbggenerated
     */
    public Date getDtmfechanacimiento() {
        return dtmfechanacimiento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_estudiantes.dtmfechanacimiento
     *
     * @param dtmfechanacimiento the value for tbl_estudiantes.dtmfechanacimiento
     *
     * @mbggenerated
     */
    public void setDtmfechanacimiento(Date dtmfechanacimiento) {
        this.dtmfechanacimiento = dtmfechanacimiento;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_estudiantes.strdireccion
     *
     * @return the value of tbl_estudiantes.strdireccion
     *
     * @mbggenerated
     */
    public String getStrdireccion() {
        return strdireccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_estudiantes.strdireccion
     *
     * @param strdireccion the value for tbl_estudiantes.strdireccion
     *
     * @mbggenerated
     */
    public void setStrdireccion(String strdireccion) {
        this.strdireccion = strdireccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_estudiantes.strtelefono
     *
     * @return the value of tbl_estudiantes.strtelefono
     *
     * @mbggenerated
     */
    public String getStrtelefono() {
        return strtelefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_estudiantes.strtelefono
     *
     * @param strtelefono the value for tbl_estudiantes.strtelefono
     *
     * @mbggenerated
     */
    public void setStrtelefono(String strtelefono) {
        this.strtelefono = strtelefono;
    }

    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_estudiantes.strciudadresidencia
     *
     * @return the value of tbl_estudiantes.strciudadresidencia
     *
     * @mbggenerated
     */
    public String getStrciudadresidencia() {
        return strciudadresidencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_estudiantes.strciudadresidencia
     *
     * @param strciudadresidencia the value for tbl_estudiantes.strciudadresidencia
     *
     * @mbggenerated
     */
    public void setStrciudadresidencia(String strciudadresidencia) {
        this.strciudadresidencia = strciudadresidencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_estudiantes.strsexo
     *
     * @return the value of tbl_estudiantes.strsexo
     *
     * @mbggenerated
     */
    public String getStrsexo() {
        return strsexo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_estudiantes.strsexo
     *
     * @param strsexo the value for tbl_estudiantes.strsexo
     *
     * @mbggenerated
     */
    public void setStrsexo(String strsexo) {
        this.strsexo = strsexo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_estudiantes.strmail
     *
     * @return the value of tbl_estudiantes.strmail
     *
     * @mbggenerated
     */
    public String getStrmail() {
        return strmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_estudiantes.strmail
     *
     * @param strmail the value for tbl_estudiantes.strmail
     *
     * @mbggenerated
     */
    public void setStrmail(String strmail) {
        this.strmail = strmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_estudiantes.dtmfecharegistro
     *
     * @return the value of tbl_estudiantes.dtmfecharegistro
     *
     * @mbggenerated
     */
    public Date getDtmfecharegistro() {
        return dtmfecharegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_estudiantes.dtmfecharegistro
     *
     * @param dtmfecharegistro the value for tbl_estudiantes.dtmfecharegistro
     *
     * @mbggenerated
     */
    public void setDtmfecharegistro(Date dtmfecharegistro) {
        this.dtmfecharegistro = dtmfecharegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_estudiantes
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TblEstudiantes other = (TblEstudiantes) that;
        return (this.getNumestudiante() == null ? other.getNumestudiante() == null : this.getNumestudiante().equals(other.getNumestudiante()))
            && (this.getStrcodigo() == null ? other.getStrcodigo() == null : this.getStrcodigo().equals(other.getStrcodigo()))
            && (this.getStridentificacion() == null ? other.getStridentificacion() == null : this.getStridentificacion().equals(other.getStridentificacion()))
            && (this.getStrtipoidentificacion() == null ? other.getStrtipoidentificacion() == null : this.getStrtipoidentificacion().equals(other.getStrtipoidentificacion()))
            && (this.getStrnombres() == null ? other.getStrnombres() == null : this.getStrnombres().equals(other.getStrnombres()))
            && (this.getDtmfechanacimiento() == null ? other.getDtmfechanacimiento() == null : this.getDtmfechanacimiento().equals(other.getDtmfechanacimiento()))
            && (this.getStrdireccion() == null ? other.getStrdireccion() == null : this.getStrdireccion().equals(other.getStrdireccion()))
            && (this.getStrtelefono() == null ? other.getStrtelefono() == null : this.getStrtelefono().equals(other.getStrtelefono()))
            && (this.getStrciudadresidencia() == null ? other.getStrciudadresidencia() == null : this.getStrciudadresidencia().equals(other.getStrciudadresidencia()))
            && (this.getStrsexo() == null ? other.getStrsexo() == null : this.getStrsexo().equals(other.getStrsexo()))
            && (this.getStrmail() == null ? other.getStrmail() == null : this.getStrmail().equals(other.getStrmail()))
            && (this.getDtmfecharegistro() == null ? other.getDtmfecharegistro() == null : this.getDtmfecharegistro().equals(other.getDtmfecharegistro()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_estudiantes
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getNumestudiante() == null) ? 0 : getNumestudiante().hashCode());
        result = prime * result + ((getStrcodigo() == null) ? 0 : getStrcodigo().hashCode());
        result = prime * result + ((getStridentificacion() == null) ? 0 : getStridentificacion().hashCode());
        result = prime * result + ((getStrtipoidentificacion() == null) ? 0 : getStrtipoidentificacion().hashCode());
        result = prime * result + ((getStrnombres() == null) ? 0 : getStrnombres().hashCode());
        result = prime * result + ((getDtmfechanacimiento() == null) ? 0 : getDtmfechanacimiento().hashCode());
        result = prime * result + ((getStrdireccion() == null) ? 0 : getStrdireccion().hashCode());
        result = prime * result + ((getStrtelefono() == null) ? 0 : getStrtelefono().hashCode());
        result = prime * result + ((getStrciudadresidencia() == null) ? 0 : getStrciudadresidencia().hashCode());
        result = prime * result + ((getStrsexo() == null) ? 0 : getStrsexo().hashCode());
        result = prime * result + ((getStrmail() == null) ? 0 : getStrmail().hashCode());
        result = prime * result + ((getDtmfecharegistro() == null) ? 0 : getDtmfecharegistro().hashCode());
        return result;
    }
}