package co.com.academica.model;

import co.com.academica.model.TblMaterias;
import co.com.academica.model.TblMaterias;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblMateriasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_materias
     *
     * @mbggenerated
     */
    int countByExample();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_materias
     *
     * @mbggenerated
     */
    int deleteByExample(TblMaterias example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_materias
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer nummateria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_materias
     *
     * @mbggenerated
     */
    int insert(TblMaterias record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_materias
     *
     * @mbggenerated
     */
    int insertSelective(TblMaterias record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_materias
     *
     * @mbggenerated
     */
    List<TblMaterias> selectByExample(TblMaterias example);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_materias
     *
     * @mbggenerated
     */
    List<TblMaterias> getMaterias(TblMaterias example);

    List<TblMaterias> getMateriasByCurso(TblMaterias a);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_materias
     *
     * @mbggenerated
     */
    TblMaterias selectByPrimaryKey(Integer nummateria);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_materias
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblMaterias record, @Param("example") TblMaterias example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_materias
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblMaterias record, @Param("example") TblMaterias example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_materias
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblMaterias record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_materias
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblMaterias record);
}