package co.com.academica.model;

import java.io.Serializable;
import java.util.Date;

public class TblMatricula implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_matricula.nummatricula
     *
     * @mbggenerated
     */
    private Integer nummatricula;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_matricula.numestudiante
     *
     * @mbggenerated
     */
    private Integer numestudiante;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_matricula.numcurso
     *
     * @mbggenerated
     */
    private Integer numcurso;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_matricula.strtipo
     *
     * @mbggenerated
     */
    private String strtipo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_matricula.dtmfecharegistro
     *
     * @mbggenerated
     */
    
    private Date dtmfecharegistro;

    private Integer startPageIndex;
    private Integer range;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_matricula
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_matricula.nummatricula
     *
     * @return the value of tbl_matricula.nummatricula
     *
     * @mbggenerated
     */
    public Integer getNummatricula() {
        return nummatricula;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_matricula.nummatricula
     *
     * @param nummatricula the value for tbl_matricula.nummatricula
     *
     * @mbggenerated
     */
    public void setNummatricula(Integer nummatricula) {
        this.nummatricula = nummatricula;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_matricula.numestudiante
     *
     * @return the value of tbl_matricula.numestudiante
     *
     * @mbggenerated
     */
    public Integer getNumestudiante() {
        return numestudiante;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_matricula.numestudiante
     *
     * @param numestudiante the value for tbl_matricula.numestudiante
     *
     * @mbggenerated
     */
    public void setNumestudiante(Integer numestudiante) {
        this.numestudiante = numestudiante;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_matricula.numcurso
     *
     * @return the value of tbl_matricula.numcurso
     *
     * @mbggenerated
     */
    public Integer getNumcurso() {
        return numcurso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_matricula.numcurso
     *
     * @param numcurso the value for tbl_matricula.numcurso
     *
     * @mbggenerated
     */
    public void setNumcurso(Integer numcurso) {
        this.numcurso = numcurso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_matricula.strtipo
     *
     * @return the value of tbl_matricula.strtipo
     *
     * @mbggenerated
     */
    public String getStrtipo() {
        return strtipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_matricula.strtipo
     *
     * @param strtipo the value for tbl_matricula.strtipo
     *
     * @mbggenerated
     */
    public void setStrtipo(String strtipo) {
        this.strtipo = strtipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_matricula.dtmfecharegistro
     *
     * @return the value of tbl_matricula.dtmfecharegistro
     *
     * @mbggenerated
     */
    public Date getDtmfecharegistro() {
        return dtmfecharegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_matricula.dtmfecharegistro
     *
     * @param dtmfecharegistro the value for tbl_matricula.dtmfecharegistro
     *
     * @mbggenerated
     */
    public void setDtmfecharegistro(Date dtmfecharegistro) {
        this.dtmfecharegistro = dtmfecharegistro;
    }

    public Integer getStartPageIndex() {
        return startPageIndex;
    }

    public void setStartPageIndex(Integer startPageIndex) {
        this.startPageIndex = startPageIndex;
    }

    public Integer getRange() {
        return range;
    }

    public void setRange(Integer range) {
        this.range = range;
    }
    
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_matricula
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TblMatricula other = (TblMatricula) that;
        return (this.getNummatricula() == null ? other.getNummatricula() == null : this.getNummatricula().equals(other.getNummatricula()))
            && (this.getNumestudiante() == null ? other.getNumestudiante() == null : this.getNumestudiante().equals(other.getNumestudiante()))
            && (this.getNumcurso() == null ? other.getNumcurso() == null : this.getNumcurso().equals(other.getNumcurso()))
            && (this.getStrtipo() == null ? other.getStrtipo() == null : this.getStrtipo().equals(other.getStrtipo()))
            && (this.getDtmfecharegistro() == null ? other.getDtmfecharegistro() == null : this.getDtmfecharegistro().equals(other.getDtmfecharegistro()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_matricula
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getNummatricula() == null) ? 0 : getNummatricula().hashCode());
        result = prime * result + ((getNumestudiante() == null) ? 0 : getNumestudiante().hashCode());
        result = prime * result + ((getNumcurso() == null) ? 0 : getNumcurso().hashCode());
        result = prime * result + ((getStrtipo() == null) ? 0 : getStrtipo().hashCode());
        result = prime * result + ((getDtmfecharegistro() == null) ? 0 : getDtmfecharegistro().hashCode());
        return result;
    }
}