package co.com.academica.model;

import java.io.Serializable;
import java.util.Date;

public class TblMaterias implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tbl_materias.nummateria
     *
     * @mbggenerated
     */
    private Integer nummateria;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tbl_materias.strnombre
     *
     * @mbggenerated
     */
    private String strnombre;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tbl_materias.numdocente
     *
     * @mbggenerated
     */
    private Integer numdocente;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tbl_materias.numcurso
     *
     * @mbggenerated
     */
    private Integer numcurso;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column tbl_materias.dtmfecharegistro
     *
     * @mbggenerated
     */
    private Date dtmfecharegistro;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database table tbl_materias
     *
     * @mbggenerated
     */
    private Integer startPageIndex;
    private Integer range;
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tbl_materias.nummateria
     *
     * @return the value of tbl_materias.nummateria
     *
     * @mbggenerated
     */
    public Integer getNummateria() {
        return nummateria;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tbl_materias.nummateria
     *
     * @param nummateria the value for tbl_materias.nummateria
     *
     * @mbggenerated
     */
    public void setNummateria(Integer nummateria) {
        this.nummateria = nummateria;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tbl_materias.strnombre
     *
     * @return the value of tbl_materias.strnombre
     *
     * @mbggenerated
     */
    public String getStrnombre() {
        return strnombre;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tbl_materias.strnombre
     *
     * @param strnombre the value for tbl_materias.strnombre
     *
     * @mbggenerated
     */
    public void setStrnombre(String strnombre) {
        this.strnombre = strnombre;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tbl_materias.numdocente
     *
     * @return the value of tbl_materias.numdocente
     *
     * @mbggenerated
     */
    public Integer getNumdocente() {
        return numdocente;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tbl_materias.numdocente
     *
     * @param numdocente the value for tbl_materias.numdocente
     *
     * @mbggenerated
     */
    public void setNumdocente(Integer numdocente) {
        this.numdocente = numdocente;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tbl_materias.numcurso
     *
     * @return the value of tbl_materias.numcurso
     *
     * @mbggenerated
     */
    public Integer getNumcurso() {
        return numcurso;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tbl_materias.numcurso
     *
     * @param numcurso the value for tbl_materias.numcurso
     *
     * @mbggenerated
     */
    public void setNumcurso(Integer numcurso) {
        this.numcurso = numcurso;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column tbl_materias.dtmfecharegistro
     *
     * @return the value of tbl_materias.dtmfecharegistro
     *
     * @mbggenerated
     */
    public Date getDtmfecharegistro() {
        return dtmfecharegistro;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column tbl_materias.dtmfecharegistro
     *
     * @param dtmfecharegistro the value for tbl_materias.dtmfecharegistro
     *
     * @mbggenerated
     */
    public void setDtmfecharegistro(Date dtmfecharegistro) {
        this.dtmfecharegistro = dtmfecharegistro;
    }

    public Integer getStartPageIndex() {
        return startPageIndex;
    }

    public void setStartPageIndex(Integer startPageIndex) {
        this.startPageIndex = startPageIndex;
    }

    public Integer getRange() {
        return range;
    }

    public void setRange(Integer range) {
        this.range = range;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table tbl_materias
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TblMaterias other = (TblMaterias) that;
        return (this.getNummateria() == null ? other.getNummateria() == null : this.getNummateria().equals(other.getNummateria()))
                && (this.getStrnombre() == null ? other.getStrnombre() == null : this.getStrnombre().equals(other.getStrnombre()))
                && (this.getNumdocente() == null ? other.getNumdocente() == null : this.getNumdocente().equals(other.getNumdocente()))
                && (this.getNumcurso() == null ? other.getNumcurso() == null : this.getNumcurso().equals(other.getNumcurso()))
                && (this.getDtmfecharegistro() == null ? other.getDtmfecharegistro() == null : this.getDtmfecharegistro().equals(other.getDtmfecharegistro()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table tbl_materias
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getNummateria() == null) ? 0 : getNummateria().hashCode());
        result = prime * result + ((getStrnombre() == null) ? 0 : getStrnombre().hashCode());
        result = prime * result + ((getNumdocente() == null) ? 0 : getNumdocente().hashCode());
        result = prime * result + ((getNumcurso() == null) ? 0 : getNumcurso().hashCode());
        result = prime * result + ((getDtmfecharegistro() == null) ? 0 : getDtmfecharegistro().hashCode());
        return result;
    }
}