package co.com.academica.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class TblUsuarios implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORACLE.TBL_USUARIOS_RENTAS.NUMUSUARIO
     *
     * @mbggenerated
     */
    private Long numusuario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORACLE.TBL_USUARIOS_RENTAS.STRLOGIN
     *
     * @mbggenerated
     */
    private String strlogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORACLE.TBL_USUARIOS_RENTAS.STRNOMBRECOMPLETO
     *
     * @mbggenerated
     */
    private String strnombrecompleto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORACLE.TBL_USUARIOS_RENTAS.STRCLAVE
     *
     * @mbggenerated
     */
    private String strclave;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORACLE.TBL_USUARIOS_RENTAS.STRROL
     *
     * @mbggenerated
     */
    private String strrol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORACLE.TBL_USUARIOS_RENTAS.STRESTADO
     *
     * @mbggenerated
     */
    private String strestado;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORACLE.TBL_USUARIOS_RENTAS.STRMAIL
     *
     * @mbggenerated
     */
    private String strmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ORACLE.TBL_USUARIOS_RENTAS
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORACLE.TBL_USUARIOS_RENTAS.NUMUSUARIO
     *
     * @return the value of ORACLE.TBL_USUARIOS_RENTAS.NUMUSUARIO
     *
     * @mbggenerated
     */
    public Long getNumusuario() {
        return numusuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORACLE.TBL_USUARIOS_RENTAS.NUMUSUARIO
     *
     * @param numusuario the value for ORACLE.TBL_USUARIOS_RENTAS.NUMUSUARIO
     *
     * @mbggenerated
     */
    public void setNumusuario(Long numusuario) {
        this.numusuario = numusuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORACLE.TBL_USUARIOS_RENTAS.STRLOGIN
     *
     * @return the value of ORACLE.TBL_USUARIOS_RENTAS.STRLOGIN
     *
     * @mbggenerated
     */
    public String getStrlogin() {
        return strlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORACLE.TBL_USUARIOS_RENTAS.STRLOGIN
     *
     * @param strlogin the value for ORACLE.TBL_USUARIOS_RENTAS.STRLOGIN
     *
     * @mbggenerated
     */
    public void setStrlogin(String strlogin) {
        this.strlogin = strlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORACLE.TBL_USUARIOS_RENTAS.STRNOMBRECOMPLETO
     *
     * @return the value of ORACLE.TBL_USUARIOS_RENTAS.STRNOMBRECOMPLETO
     *
     * @mbggenerated
     */
    public String getStrnombrecompleto() {
        return strnombrecompleto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORACLE.TBL_USUARIOS_RENTAS.STRNOMBRECOMPLETO
     *
     * @param strnombrecompleto the value for ORACLE.TBL_USUARIOS_RENTAS.STRNOMBRECOMPLETO
     *
     * @mbggenerated
     */
    public void setStrnombrecompleto(String strnombrecompleto) {
        this.strnombrecompleto = strnombrecompleto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORACLE.TBL_USUARIOS_RENTAS.STRCLAVE
     *
     * @return the value of ORACLE.TBL_USUARIOS_RENTAS.STRCLAVE
     *
     * @mbggenerated
     */
    public String getStrclave() {
        return strclave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORACLE.TBL_USUARIOS_RENTAS.STRCLAVE
     *
     * @param strclave the value for ORACLE.TBL_USUARIOS_RENTAS.STRCLAVE
     *
     * @mbggenerated
     */
    public void setStrclave(String strclave) {
        this.strclave = strclave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORACLE.TBL_USUARIOS_RENTAS.STRROL
     *
     * @return the value of ORACLE.TBL_USUARIOS_RENTAS.STRROL
     *
     * @mbggenerated
     */
    public String getStrrol() {
        return strrol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORACLE.TBL_USUARIOS_RENTAS.STRROL
     *
     * @param strrol the value for ORACLE.TBL_USUARIOS_RENTAS.STRROL
     *
     * @mbggenerated
     */
    public void setStrrol(String strrol) {
        this.strrol = strrol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORACLE.TBL_USUARIOS_RENTAS.STRESTADO
     *
     * @return the value of ORACLE.TBL_USUARIOS_RENTAS.STRESTADO
     *
     * @mbggenerated
     */
    public String getStrestado() {
        return strestado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORACLE.TBL_USUARIOS_RENTAS.STRESTADO
     *
     * @param strestado the value for ORACLE.TBL_USUARIOS_RENTAS.STRESTADO
     *
     * @mbggenerated
     */
    public void setStrestado(String strestado) {
        this.strestado = strestado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORACLE.TBL_USUARIOS_RENTAS.STRMAIL
     *
     * @return the value of ORACLE.TBL_USUARIOS_RENTAS.STRMAIL
     *
     * @mbggenerated
     */
    public String getStrmail() {
        return strmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORACLE.TBL_USUARIOS_RENTAS.STRMAIL
     *
     * @param strmail the value for ORACLE.TBL_USUARIOS_RENTAS.STRMAIL
     *
     * @mbggenerated
     */
    public void setStrmail(String strmail) {
        this.strmail = strmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORACLE.TBL_USUARIOS_RENTAS
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TblUsuarios other = (TblUsuarios) that;
        return (this.getNumusuario() == null ? other.getNumusuario() == null : this.getNumusuario().equals(other.getNumusuario()))
            && (this.getStrlogin() == null ? other.getStrlogin() == null : this.getStrlogin().equals(other.getStrlogin()))
            && (this.getStrnombrecompleto() == null ? other.getStrnombrecompleto() == null : this.getStrnombrecompleto().equals(other.getStrnombrecompleto()))
            && (this.getStrclave() == null ? other.getStrclave() == null : this.getStrclave().equals(other.getStrclave()))
            && (this.getStrrol() == null ? other.getStrrol() == null : this.getStrrol().equals(other.getStrrol()))
            && (this.getStrestado() == null ? other.getStrestado() == null : this.getStrestado().equals(other.getStrestado()))
            && (this.getStrmail() == null ? other.getStrmail() == null : this.getStrmail().equals(other.getStrmail()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORACLE.TBL_USUARIOS_RENTAS
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getNumusuario() == null) ? 0 : getNumusuario().hashCode());
        result = prime * result + ((getStrlogin() == null) ? 0 : getStrlogin().hashCode());
        result = prime * result + ((getStrnombrecompleto() == null) ? 0 : getStrnombrecompleto().hashCode());
        result = prime * result + ((getStrclave() == null) ? 0 : getStrclave().hashCode());
        result = prime * result + ((getStrrol() == null) ? 0 : getStrrol().hashCode());
        result = prime * result + ((getStrestado() == null) ? 0 : getStrestado().hashCode());
        result = prime * result + ((getStrmail() == null) ? 0 : getStrmail().hashCode());
        return result;
    }
}