package co.com.academica.model;

import co.com.academica.model.TblUsuarios;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblUsuariosMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ORACLE.TBL_USUARIOS_RENTAS
     *
     * @mbggenerated
     */
    int countByExample();

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ORACLE.TBL_USUARIOS_RENTAS
     *
     * @mbggenerated
     */
    int deleteByExample(TblUsuarios example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ORACLE.TBL_USUARIOS_RENTAS
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long numusuario);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ORACLE.TBL_USUARIOS_RENTAS
     *
     * @mbggenerated
     */
    int insert(TblUsuarios record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ORACLE.TBL_USUARIOS_RENTAS
     *
     * @mbggenerated
     */
    int insertSelective(TblUsuarios record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ORACLE.TBL_USUARIOS_RENTAS
     *
     * @mbggenerated
     */
    List<TblUsuarios> selectByExample(TblUsuarios example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ORACLE.TBL_USUARIOS_RENTAS
     *
     * @mbggenerated
     */
    TblUsuarios selectByPrimaryKey(Long numusuario);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ORACLE.TBL_USUARIOS_RENTAS
     *
     * @mbggenerated
     */
    List<TblUsuarios> getUsuarios();

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ORACLE.TBL_USUARIOS_RENTAS
     *
     * @mbggenerated
     */
    TblUsuarios getByLogin(TblUsuarios user);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ORACLE.TBL_USUARIOS_RENTAS
     *
     * @mbggenerated
     */
    int insertUsuario(TblUsuarios user);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ORACLE.TBL_USUARIOS_RENTAS
     *
     * @mbggenerated
     */
    int updateUsuario(TblUsuarios user);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ORACLE.TBL_USUARIOS_RENTAS
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblUsuarios record, @Param("example") TblUsuarios example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ORACLE.TBL_USUARIOS_RENTAS
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblUsuarios record, @Param("example") TblUsuarios example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ORACLE.TBL_USUARIOS_RENTAS
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblUsuarios record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ORACLE.TBL_USUARIOS_RENTAS
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblUsuarios record);
}